"""
测试配置模块

注意：由于 config.py 依赖 config.yaml 文件，
这些测试需要创建临时配置文件。
"""
import tempfile
from pathlib import Path
import pytest


class TestConfigRequiresYaml:
    """测试配置需要 config.yaml"""

    def test_get_config_path_raises_if_missing(self):
        """config.yaml 不存在时抛出 FileNotFoundError"""
        from src import config as config_module
        original_func = config_module._get_config_path

        def fake_get_config_path():
            raise FileNotFoundError("配置文件不存在")

        config_module._get_config_path = staticmethod(fake_get_config_path)

        try:
            with pytest.raises(FileNotFoundError):
                config_module._load_yaml()
        finally:
            config_module._get_config_path = original_func


class TestConfigYamlLoading:
    """测试 YAML 配置加载功能"""

    @pytest.fixture
    def complete_yaml_content(self):
        """完整的 config.yaml 内容"""
        return """crawler:
  page_load_timeout: 30000
  timeout: 30000
  scroll_wait_ms: 500
  browser_close_delay: 0.25
  user_agents: []

document_style:
  title_font_size: 18
  code_font_size: 10
  image_width: 5.0
  inline_image_width: 4.0
  footer_mark: "Generated by Doubao Export"

global:
  url_fallback_length: 20
  concurrency: 3

index:
  max_age_days: 10

pandoc:
  timeout: 15

parser:
  latex_attr: "copy-text"
"""

    def test_load_yaml_with_temp_file(self, tmp_path, complete_yaml_content):
        """
        验证正常加载临时 YAML 文件
        
        创建包含完整配置的临时 YAML 文件，
        调用 _load_yaml() 验证返回正确的 dict。
        """
        import yaml
        from src import config as config_module
        
        # 创建临时配置文件
        config_file = tmp_path / "config.yaml"
        config_file.write_text(complete_yaml_content, encoding='utf-8')
        
        # Mock _get_config_path 返回临时文件路径
        original_func = config_module._get_config_path
        config_module._get_config_path = lambda: config_file
        
        try:
            result = config_module._load_yaml()
            
            # 验证返回的是 dict 类型
            assert isinstance(result, dict)
            # 验证关键配置存在
            assert "crawler" in result
            assert "document_style" in result
            assert result["crawler"]["page_load_timeout"] == 30000
        finally:
            config_module._get_config_path = original_func

    def test_load_yaml_file_not_found(self, tmp_path):
        """
        验证文件不存在时抛出 FileNotFoundError
        
        当 _get_config_path 返回不存在的路径时，
        _load_yaml() 应抛出 FileNotFoundError。
        """
        from src import config as config_module
        
        # 创建指向不存在文件的路径
        non_existent_path = tmp_path / "non_existent_config.yaml"
        
        original_func = config_module._get_config_path
        config_module._get_config_path = lambda: non_existent_path
        
        try:
            with pytest.raises(FileNotFoundError) as exc_info:
                config_module._load_yaml()
            
            assert "不存在" in str(exc_info.value) or "non_existent" in str(exc_info.value)
        finally:
            config_module._get_config_path = original_func

    def test_load_yaml_empty_file(self, tmp_path):
        """
        验证空文件时抛出 ValueError
        
        当配置文件为空时，_load_yaml() 应抛出 ValueError。
        """
        from src import config as config_module
        
        # 创建空文件
        empty_file = tmp_path / "empty_config.yaml"
        empty_file.write_text("", encoding='utf-8')
        
        original_func = config_module._get_config_path
        config_module._get_config_path = lambda: empty_file
        
        try:
            with pytest.raises(ValueError) as exc_info:
                config_module._load_yaml()
            
            assert "空" in str(exc_info.value)
        finally:
            config_module._get_config_path = original_func

    def test_validate_config_missing_section(self):
        """
        验证缺少节时抛出 KeyError
        
        当配置 dict 缺少必需的节（如 crawler, document_style 等）时，
        _validate_config() 应抛出 KeyError。
        """
        from src import config as config_module
        
        # 缺少必需节
        incomplete_data = {
            "crawler": {},
            # 缺少 document_style, index, pandoc, parser, global
        }
        
        with pytest.raises(KeyError) as exc_info:
            config_module._validate_config(incomplete_data)
        
        # 验证错误消息包含缺失的节名
        error_msg = str(exc_info.value)
        assert "document_style" in error_msg or "index" in error_msg or "pandoc" in error_msg

    def test_require_keys_missing(self):
        """
        验证缺少字段时抛出 KeyError
        
        当配置 dict 缺少必需的字段时，
        _require_keys() 应抛出 KeyError。
        """
        from src import config as config_module
        
        # 缺少必需字段
        incomplete_data = {
            "page_load_timeout": 30000,
            # 缺少 scroll_wait_ms, browser_close_delay, user_agents
        }
        
        with pytest.raises(KeyError) as exc_info:
            config_module._require_keys(
                incomplete_data,
                ["page_load_timeout", "scroll_wait_ms", "browser_close_delay", "user_agents"],
                "crawler"
            )
        
        error_msg = str(exc_info.value)
        assert "scroll_wait_ms" in error_msg

    def test_load_complete_config_integration(self, tmp_path, complete_yaml_content):
        """
        完整集成测试：使用临时配置文件加载 GlobalConfig
        
        创建包含完整配置的临时 config.yaml，
        通过 GlobalConfig.load() 验证返回完整的配置对象。
        """
        import yaml
        from src import config as config_module
        
        # 创建临时配置文件
        config_file = tmp_path / "config.yaml"
        config_file.write_text(complete_yaml_content, encoding='utf-8')
        
        # Mock _get_config_path
        original_func = config_module._get_config_path
        config_module._get_config_path = lambda: config_file
        
        # 重置全局配置缓存
        original_config = config_module._config
        config_module._config = None
        
        try:
            # 加载配置
            config = config_module.GlobalConfig.load()
            
            # 验证各配置节正确加载
            assert isinstance(config.crawler, config_module.CrawlerConfig)
            assert config.crawler.page_load_timeout == 30000
            assert config.crawler.scroll_wait_ms == 500
            assert config.crawler.browser_close_delay == 0.25
            
            assert isinstance(config.document_style, config_module.DocumentStyleConfig)
            assert config.document_style.title_font_size == 18
            assert config.document_style.code_font_size == 10
            
            assert isinstance(config.index, config_module.IndexConfig)
            assert config.index.max_age_days == 10
            
            assert isinstance(config.pandoc, config_module.PandocConfig)
            assert config.pandoc.timeout == 15
            
            assert isinstance(config.parser, config_module.ParserConfig)
            assert config.parser.latex_attr == "copy-text"
            
            assert config.url_fallback_length == 20
            assert config.concurrency == 3
        finally:
            config_module._get_config_path = original_func
            config_module._config = original_config


class TestConfigClasses:
    """测试配置数据类"""

    def test_crawler_config_dataclass(self):
        """CrawlerConfig 应为 dataclass"""
        from src.config import CrawlerConfig
        cfg = CrawlerConfig(
            page_load_timeout=30000,
            timeout=30000,
            scroll_wait_ms=500,
            browser_close_delay=0.25,
            user_agents=["test-agent"]
        )
        assert cfg.page_load_timeout == 30000
        assert cfg.scroll_wait_ms == 500

    def test_document_style_config_dataclass(self):
        """DocumentStyleConfig 应为 dataclass"""
        from src.config import DocumentStyleConfig
        cfg = DocumentStyleConfig(
            title_font_size=18,
            code_font_size=10,
            image_width=5.0,
            inline_image_width=4.0,
            footer_mark="Generated by Doubao Export"
        )
        assert cfg.title_font_size == 18

    def test_index_config_dataclass(self):
        """IndexConfig 应为 dataclass"""
        from src.config import IndexConfig
        cfg = IndexConfig(max_age_days=10)
        assert cfg.max_age_days == 10

    def test_pandoc_config_dataclass(self):
        """PandocConfig 应为 dataclass"""
        from src.config import PandocConfig
        cfg = PandocConfig(timeout=15)
        assert cfg.timeout == 15

    def test_parser_config_dataclass(self):
        """ParserConfig 应为 dataclass"""
        from src.config import ParserConfig
        cfg = ParserConfig(latex_attr="data-latex")
        assert cfg.latex_attr == "data-latex"

    def test_global_config_dataclass(self):
        """GlobalConfig 应为 dataclass"""
        from src.config import (
            CrawlerConfig, DocumentStyleConfig, IndexConfig,
            PandocConfig, ParserConfig, GlobalConfig
        )
        cfg = GlobalConfig(
            crawler=CrawlerConfig(30000, 30000, 500, 0.25, []),
            document_style=DocumentStyleConfig(18, 10, 5.0, 4.0, ""),
            index=IndexConfig(10),
            pandoc=PandocConfig(15),
            parser=ParserConfig("data-latex"),
            url_fallback_length=20,
            concurrency=3
        )
        assert cfg.url_fallback_length == 20
        assert cfg.concurrency == 3